set.seed(1)
y.mat.sim <- matrix(sample(1:3,50*1000,replace=TRUE),nrow=1000)

set.seed(10)
Rprof("profile_matrix.out", line.profiling=TRUE)
eval(parse("R/example_biclustering_matrix.R", keep.source=TRUE))
Rprof(NULL)
set.seed(10)
Rprof("profile_for.out", line.profiling=TRUE)
eval(parse("R/example_biclustering_for.R", keep.source=TRUE))
Rprof(NULL)
summaryRprof("profile_matrix.out", lines="show")
summaryRprof("profile_for.out", lines="show")