# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_clustord_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_clustord_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_clustord_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_clustord_rcpparma_bothproducts`, x)
}

rcpparma_updateliC <- function(li, columnclusters, RG, n, p, ymat, theta, pivec, kappavec) {
    .Call(`_clustord_rcpparma_updateliC`, li, columnclusters, RG, n, p, ymat, theta, pivec, kappavec)
}

rcpparma_updateliR <- function(li, rowclusters, CG, n, p, ymat, theta, pivec, kappavec) {
    .Call(`_clustord_rcpparma_updateliR`, li, rowclusters, CG, n, p, ymat, theta, pivec, kappavec)
}

rcpparma_Rclusterll <- function(ymat, theta, pprm, piv, RG, p, n, partial) {
    .Call(`_clustord_rcpparma_Rclusterll`, ymat, theta, pprm, piv, RG, p, n, partial)
}

